### PR TITLE
Fix Portuguese plone.app.locales 5.1.x (Plone 5.2)

### LINKED ISSUE #414: Plone 5.2 portuguese
**Describe the bug**
Plone 5.2 is not translated to portuguese if the site language is portuguese.

**To Reproduce**

- Create a Plone 5.2 vanilla site with site language portuguese.

**Expected behavior**
UI is translated.

**Screenshots**

**Software (please complete the following information):**

- Plone Version 5.2.13
- plone.app.locales branch 5.1.x (Plone 5.2 comes with plone.app.locales 5.1.33)

**Additional context**
Other site languages like italiano and german do translate the UI. 
Other languages like norsk do NOT translate the language.

### PR DESCRIPTION
**Pull request by ksuess**
Fix #414 

- [x] Remove fuzzy entries
- [x] Fix language values

### CODE REVIEW

**Review by erral — APPROVED** [review]

**Comment by ksuess** [comment]
Even if this is not a necessary fix, I think this clean up would make sense to merge. 
If you aggree, feel free to merge. Otherwise this can be closed.

**Comment by erral** [comment]
Do you need a new release of this branch? I will be happy to do so.

**Comment by ksuess** [comment]
Well, yes, I think a release of plone.app.locales 5.1.x would be a clean and healthy state for portuguese translations for Plone 5.2. 
Even if there will be no further release of Plone 5.2.x.
Thank you @erral!

**Comment by erral** [comment]
I have just released 5.1.34 https://pypi.org/project/plone.app.locales/5.1.34/

**Comment by ksuess** [comment]
Wow, that was fast. You're the best.

**Pull request merged**
