### PR TITLE
resync po files to include the 7 messages from plone.app.contenttypes…

### PR DESCRIPTION
**Pull request by claytonc**
… and updated Brazilian Portuguese translation

### CODE REVIEW

**Comment by vincentfretin** [comment]
How did you resync that? Do you have a i18ndude checkout in your buildout? I see the two messages from lockingbehaviour now has line information and it's supported only on i18ndude maurits-extract-zcml branch AFAICT https://github.com/collective/i18ndude/pull/31

**Comment by claytonc** [comment]
I always use this command:
i18ndude sync --pot plone.pot */LC_MESSAGES/plone.po

**Comment by vincentfretin** [comment]
Ok. And how do you update plone.pot?
You should normally use this from buildout.coredev:
bin/buildout -c experimental/i18n.cfg
bin/i18n plone
It takes care of the i18ndude rebuilt-pot and sync commands.

**Comment by claytonc** [comment]
Very Good, next sync I will use the command up.

**Comment by vincentfretin** [comment]
@claytonc How did you do to create the plone.pot ? Which version of i18ndude did you use? You was apparently able to extract messages from plone.app.contenttypes/plone/app/contenttypes/behaviors/configure.zcml but when I try to execute bin/plone i18n again with i18ndude master or branch=maurits-extract-zcml I lose them. (refs https://github.com/collective/i18ndude/pull/31)

**Comment by vincentfretin** [comment]
@claytonc Did you put them in plone.pot manually?

**Comment by vincentfretin** [comment]
Where did "Plone Leftcolumn", "Plone Footerportlets", "Plone Rightcolumn" come from? I remove them and put the 7 messages from plone.app.contenttypes/plone/app/contenttypes/behaviors/configure.zcml in plone-manual.pot.

**Pull request merged**
