### PR TITLE
Include plone.app.caching translations

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by vincentfretin** [comment]
You will need to remove the files in locales-addons too.

**Comment by vincentfretin** [comment]
@erral did you check that all messages in plone/app/locales/locales-addons/plone.app.caching-manual.pot are in the generated plone.pot?  It may be the case now with the i18ndude we use that include messages from zcml, but can you please double check? If some strings are not added, you will need to put them in plone-manual.pot and get the previous translations back with some i18ndude admix commands.

**Comment by erral** [comment]
Ok, let me look at it.

**Comment by erral** [comment]
You were right. Some msgids were present but some of them were not because I did not change the i18n_domain in a zcml file. 

Anyway I recovered the translations and I will add them now. I see that the msgids that were present in plone.app.caching-manual.pot are now correctly discovered by i18ndude and are present in plone.pot.

**Comment by erral** [comment]
I also see that the same plone.app.caching version is being used for Plone 5.0.x, so I will add the msgids there too.

**Comment by vincentfretin** [comment]
Cool, thanks! Verify you didn't forget the domain in zcml in other packages then ;)

**Comment by erral** [comment]
One multilingual string is missing, I'm working on it right now.

**Pull request merged**
