### PR TITLE
Update plonefrontpage.pot

### PR DESCRIPTION
**Pull request by polyester**
use https, bring in line with Products.CMFPlone master

### CODE REVIEW

**Comment by vincentfretin** [comment]
Can you please update the links on all the translations? This will avoid to mark the all translations as fuzzy.

**Comment by polyester** [comment]
will do.

**Comment by polyester** [comment]
changed links, and removed some old links where it was obvious I can do that. There's still a bunch of languages with old links (to zope2.zope.org for instance) but you need actual language skills to change that part. I did include the up-to-date 'default' English text in each plonefrontpage.po so translators have the current default.

**Comment by vincentfretin** [comment]
Thanks.

**Pull request merged**
