### PR TITLE
French translation polished, revised and completed

### PR DESCRIPTION
**Pull request by dbitouze**

### CODE REVIEW

**Comment by ale-rt** [comment]
Hello! It seems that since this PR was merged the jenkins job are failing with an error on PAM.
See for example https://github.com/plone/plone.app.users/issues/78.
It seems that the page is not translated.

Note that I was not able to reproduce the error locally until I removed the compiled mo files in my checkout of plone.app.locales.
After running the tests I see that the `plone.mo` file is missing:
```
[ale@emily locales]$ ls -lrt ./locales/fr/LC_MESSAGES/*.mo
-rw-rw-r-- 1 ale ale  5699 Jun 11 14:50 ./locales/fr/LC_MESSAGES/cmfeditions.mo
-rw-rw-r-- 1 ale ale  2353 Jun 11 14:50 ./locales/fr/LC_MESSAGES/plonelocales.mo
-rw-rw-r-- 1 ale ale  6306 Jun 11 14:50 ./locales/fr/LC_MESSAGES/plonefrontpage.mo
-rw-rw-r-- 1 ale ale  7382 Jun 11 14:50 ./locales/fr/LC_MESSAGES/cmfplacefulworkflow.mo
-rw-rw-r-- 1 ale ale 16908 Jun 11 14:50 ./locales/fr/LC_MESSAGES/widgets.mo
-rw-rw-r-- 1 ale ale  2383 Jun 11 14:50 ./locales/fr/LC_MESSAGES/atreferencebrowserwidget.mo
-rw-rw-r-- 1 ale ale 14329 Jun 11 14:50 ./locales/fr/LC_MESSAGES/atcontenttypes.mo
```

Can anybody have a look back on this? 
I see that the french translations have some "fuzzy"ness inside, but I do not think that is the issue.
Maybe some character is breaking the pocompiler?

**Comment by ebrehault** [comment]
Hi @dbitouze , I did not see anything weird in your last changes but still it looks like something is wrong somewhere.
Could you have a look please?

**Comment by ale-rt** [comment]
I think this fixes it: https://github.com/collective/plone.app.locales/pull/254/files

**Comment by dbitouze** [comment]
>Hi @dbitouze , I did not see anything weird in your last changes but still it looks like something is wrong somewhere.
Could you have a look please?

@ebrehault Hopefully, @ale-rt detected what was wrong: thanks, I guess I couldn't find it by myself.

**Comment by ebrehault** [comment]
Tout est bien qui finit bien :)

**Comment by ale-rt** [comment]
Merci beaucoup! I merged https://github.com/collective/plone.app.locales/pull/254.

**Pull request merged**
