### PR TITLE
French: better translation in folder contents pagination

### PR DESCRIPTION
**Pull request by vincentfretin**
Before:
Capture d’écran de 2020-06-21 11-31-10

After:
Capture d’écran de 2020-06-21 11-30-28

### CODE REVIEW

**Comment by dbitouze** [comment]
I guess there is only one page displayed at a time, hence "affichée" should be in singular form only. BTW, maybe a better wording would be "Page affichée : X sur Y".

**Comment by vincentfretin** [comment]
Of course singular!
For the better wording, indeed this would be better but this requires some changes in the js, I'm not going to take time for that.
Actually we could also just not translate "shown" (use just a space), so it just shows "Page : 1 sur 1". What do you think?

**Comment by dbitouze** [comment]
> For the better wording, indeed this would be better but this requires some changes in the js, I'm not going to take time for that.

I can understand :)

> Actually we could also just not translate "shown" (use just a space), so it just shows "Page : 1 sur 1". What do you think?

Looks good but I would remove the colon: "Page 1 sur 1".

**Comment by vincentfretin** [comment]
Capture d’écran de 2020-06-22 16-40-39

**Pull request merged**
