### PR TITLE
Please merge for this po files for Japanese

### PR DESCRIPTION
**Pull request by terapyon**

### CODE REVIEW

**Comment by pbauer** [comment]
@terapyon can you please rebase you pr so it can be merged?

**Comment by terapyon** [comment]
@pbauer Please merge this PR. Conflict was resolved by removing the file.

**Comment by jensens** [comment]
sorry @terapyon, since plone.app.locale is not in "plone" organisation it was not on my radar for PR merges. May you please rebase again so we can merge it asap?

**Comment by terapyon** [comment]
@jensens Thank you for your message. I just merged by myself.

**Comment by pbauer** [comment]
:fireworks:

**Pull request merged**
