### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by serge73**
russian plone.po update

### CODE REVIEW

**Comment by jensens** [comment]
thanks, but before merge, please add a line to https://github.com/collective/plone.app.locales/blob/master/CHANGES.rst

**Comment by thet** [comment]
Also, Plone Core Contributor Agreement is missing. Also here: https://github.com/plone/plone.dexterity/pull/48

**Comment by jensens** [comment]
FYI: for plone.app.locales such is not needed, this is the reason the package resides in collective.
for all packages in plone organization Plone Core Contributor Agreement is mandatory.

**Comment by thet** [comment]
True! Sorry for confusing that. True for plone.app.locales, but not plone.dexterity. Regarding to https://plone.org/foundation/materials/foundation-resolutions/patch-policy-052011 also translations need the contributor agreement, because they are not listed as exceptions to the rule. But @serge73 already signed and mailed...

**Pull request merged**
