### PR TITLE
Updated Language-Codes in po file headers.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
These headers are not used in Plone to determine the language: that is done by inspecting the directory name.  But the i18ndude script uses the Language-Code header when printing statistics.  Several were set to en or to for example zh_CN (as the directory name should be) instead of zh-cn (as the language code should be).
See https://community.plone.org/t/i-set-personal-preferrence-language-to-my-preferred-lanaguage-but-the-gui-still-shows-english/1411/9

When I run `i18ndude list -p plone` (like in http://stackoverflow.com/a/36976256/621201) the difference before and after this change is:

```
$ diff old new
11c11
<   0% - Chinese (China) (zh-cn)
---
>  73% - Chinese (China) (zh-cn)
24c24
<   0% - Swedish (sv)
---
>  63% - Swedish (sv)
57d56
<  73% - Chinese Simplified (zh_CN)
```

This means that the statistics for Chinese and Swedish have been fixed: they are no longer double in the list, with zero percent on the first mention.  The full output is then:

```
Messages: 2688

Tier 1:

100% - English (en)
 93% - French (fr)
 92% - Italian (it)
 73% - German (de)
 89% - Spanish (es)
 74% - Dutch (nl)
 73% - Chinese (China) (zh-cn)
 94% - Chinese (Taiwan) (zh-tw)
 80% - Japanese (ja)
 10% - Korean (ko)
 94% - Portuguese (Brazil) (pt-br)
 78% - Russian (ru)
 58% - Polish (pl)
 52% - Turkish (tr)
 13% - Thai (th)
 39% - Arabic (ar)

Tier 2:

 63% - Swedish (sv)
 58% - Finnish (fi)
 87% - Danish (da)
 49% - Portuguese (pt)
 61% - Romanian (ro)
 37% - Hungarian (hu)
 41% - Hebrew (he)
 42% - Indonesian (id)
 70% - Czech (cs)
 28% - Greek (el)
 53% - Norwegian (no)
 47% - Vietnamese (vi)
 47% - Bulgarian (bg)
  9% - Croatian (hr)
 37% - Lithuanian (lt)
 54% - Slovak (sk)
  0% - Tagalog (tl)
 82% - Slovenian (sl)
 22% - Serbian (sr)
 63% - Catalan (ca)
 30% - Latvian (lv)
 87% - Ukrainian (uk)
  7% - Hindi (hi)

Tier 3:

 55% - Afrikaans (af)
  3% - Albanian (sq)
  9% - Armenian (hy)
100% - Basque (eu)
  8% - Bengali (bn)
 18% - Burmese (my)
 16% - Chinese (Hongkong) (zh-hk)
 53% - Esperanto (eo)
 18% - Estonian (et)
 17% - Furlan (fu)
 39% - Galician (gl)
 16% - Georgian (ka)
 15% - Kannada (kn)
 22% - Macedonian (mk)
  9% - Nynorsk (nn)
 18% - Persian (fa)
  8% - Tamil (ta)
  8% - Telugu (te)
 18% - Welsh (cy)
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Since this changes a lot of files, let me run a Jenkins test for good measure:
http://jenkins.plone.org/job/pull-request-5.1/189/

**Comment by mauritsvanrees** [comment]
I am getting a strange Jenkins error that is totally unrelated (`github.GithubException.UnknownObjectException`).
I'll try again on Plone 5.0: http://jenkins.plone.org/job/pull-request-5.0/1150/
No, that leads to the same error. Maybe this pull request job does not work for packages from the collective, or there is some temporary problem on github or Jenkins.
I think we can ignore this.

**Comment by gforcada** [comment]
@mauritsvanrees matbe I hardcoded plone org somewhere, let me take a look

**Comment by gforcada** [comment]
@mauritsvanrees it seems to be a permission problem, @mister-roboto is not member of collective and so can not add status to commits, I will try to sort it out with @tisto

**Comment by gforcada** [comment]
@mauritsvanrees fixed :-) Jenkins job is running http://jenkins.plone.org/job/pull-request-5.1/246 although it cannot update the status so far :-/

**Pull request merged**
