### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by dbitouze**

### CODE REVIEW

**Comment by vincentfretin** [comment]
There are new messages to be translated and some fuzzy since I resynced the po files.
You can search for `fuzzy` and `msgstr ""` in the file.

**Comment by dbitouze** [comment]
Fuzzy translations
----------------
All are OK IMHO except maybe:
```
#. Default: "/old-home-page.asp,/front-page,2019/01/27 10:42:59 GMT+1,true<br /> /people/JoeT,/Users/joe-thurston,2018-12-31,false"
#: CMFPlone/controlpanel/browser/redirects-controlpanel.pt:157
#, fuzzy
msgid "example_bulk_upload"
msgstr "/old-home-page.asp,/front-page<br />/people/JoeT,/Users/joe-thurston"
```
but I don't know the context so I don't know what a better translation would be.

Untranslated messages
----------------
```
#: CMFPlone/controlpanel/browser/redirects-controlpanel.pt:233
msgid "Both"
```
has been translated by:
`msgstr "Les deux"`
but maybe I'm wrong ("L'un et l'autre"? "Ensemble"? Etc.: without the context, I'm cannot be sure).

```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:31
msgid "monthly_day_of_month_4"
msgstr ""
```
I don't know how to translate this message.

```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:128
msgid "no_end_after_n_occurrences"
msgstr ""
```
```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:124
msgid "no_repeat_every"
msgstr ""
```
```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:126
msgid "no_repeat_on"
msgstr ""
```
```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:120
msgid "no_template_match"
msgstr ""
```
```
#: plone.app.registry/plone/app/registry/browser/templates/records.pt:153
msgid "registry_add_record_text"
msgstr ""
```
```
#: plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py:119
msgid "unsupported_features"
msgstr ""

```I'm not sure how to translate these messages.

**Comment by vincentfretin** [comment]
"Les deux" for "Both" is good, it means both "Automatically" and "Manually". The context is the new url redirect page "Gestion des URL"￼
"http://localhost:8080/Plone/@@redirection-controlpanel"

**Comment by vincentfretin** [comment]
I'm fixing the remaining fuzzies right now.

**Comment by vincentfretin** [comment]
https://github.com/collective/plone.app.locales/commit/15ca9cb613fc6598860e2693fbe75055bad78125 and https://github.com/collective/plone.app.locales/commit/afebdd89f54dfc3a12ffe4212226706c4e8635dc

**Comment by vincentfretin** [comment]
```
#: plone.app.registry/plone/app/registry/browser/templates/records.pt:153
msgid "registry_add_record_text"
msgstr ""
```
The i18n:translate in this records.pt template translate nothing AFAICT. This should be deleted in the template. Can you please do a PR to remove it or create a ticket for it?

For the messages coming from i18n.py see https://github.com/plone/Products.CMFPlone/issues/2897

**Comment by dbitouze** [comment]
>The i18n:translate in this records.pt template translate nothing AFAICT. This should be deleted in the template. Can you please do a PR to remove it or create a ticket for it?

I'm sorry: I'm not sure of what I'm supposed to do. If someone else wants to proceed, please proceed!

**Pull request merged**
