### PR TITLE
Add removed translation from Plone 5.1 to Plone 5.2

### PR DESCRIPTION
**Pull request by anuyens**
Add removed msgid from Plone 5.1 to Plone 5.2

### CODE REVIEW

**Comment by agitator** [comment]
lgtm

**Comment by agitator** [comment]
I think it's better this way, then trying to keep different translation branches in sync

**Comment by anuyens** [comment]
Thank's for code reviewing and merged pull request.
@vincentfretin : Hello you, I do this follow a discussion with phillippe on sprint.
Have a nice day

**Comment by vincentfretin** [comment]
The added messages had "Default: plone" and so generated lots of fuzzy. I did again the work by putting the removed messages in plone-manual.pot.

**Pull request merged**
